// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";

import env, { required } from "@monorepo/core/src/env.js";

const SUPABASE_URL = required(env.SUPABASE_PROJECT_URL);
const SUPABASE_PUBLISHABLE_KEY = required(env.SUPABASE_API_KEY_SECRET);

const options = {
  db: {
    schema: "public",
  },
  auth: {
    autoRefreshToken: false,
  },
};

export const supabaseClient = createClient(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  options
);
